#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# If the control reaches this step, the placeholder service can be enabled.

systemctl --user daemon-reload
systemctl --user enable --now grantora.service
