#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# If the control reaches this step, the runtime skeleton can be enabled.

systemctl --user daemon-reload
systemctl --user enable grantora.service
systemctl --user restart grantora.service
