#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

cat >/dev/null

systemctl --user disable --now grantora.service || true
systemctl --user stop grantora-apisix.service grantora-api.service || true
systemctl --user stop grantora-apisix-etcd.service grantora-postgres.service || true
systemctl --user stop grantora-pod.service || true
